# Need to create EMPLOYEE and PASSWORD tables

CREATE TABLE CATEGORY
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(30) /*UNIQUE NOT NULL*/
);

CREATE TABLE PRODUCT
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(100),
  description VARCHAR(255),
  price DOUBLE UNSIGNED,
  disabled TINYINT(1) UNSIGNED DEFAULT '0',
  category_id BIGINT(20) NOT NULL,
  CONSTRAINT fk_category_id FOREIGN KEY(category_id) REFERENCES CATEGORY(id)
);

# CREATE TABLE STOCK
# (
#   id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
#   amount INTEGER NOT NULL,
#   product_id BIGINT(20) NOT NULL,
#   CONSTRAINT fk1_product_id FOREIGN KEY(product_id) REFERENCES PRODUCT(id)
# );

# CREATE TABLE ADDRESS (
#   id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
#   country VARCHAR(50),
#   region VARCHAR(50),
#   city VARCHAR(50),
#   street VARCHAR(50),
#   house VARCHAR(50),
#   apartment INTEGER
# );

CREATE TABLE CUSTOMER
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  country VARCHAR(50),
  region VARCHAR(50),
  city VARCHAR(50),
  street VARCHAR(50),
  house VARCHAR(50),
  apartment INTEGER
#   address_id BIGINT(20) NOT NULL,
#   CONSTRAINT fk1_address_id FOREIGN KEY(address_id) REFERENCES ADDRESS(id)
);

CREATE TABLE CART
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  created TIMESTAMP DEFAULT NOW(),
  modified TIMESTAMP DEFAULT NOW(),
  expired TINYINT(1) UNSIGNED DEFAULT '0',
  customer_id BIGINT(20) NOT NULL,
  CONSTRAINT fk1_customer_id FOREIGN KEY(customer_id) REFERENCES CUSTOMER(id)
);

CREATE TABLE CART_ENTRY
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  amount INTEGER NOT NULL,
  product_id BIGINT(20) NOT NULL,
  cart_id BIGINT(20) NOT NULL,
  CONSTRAINT fk2_product_id FOREIGN KEY(product_id) REFERENCES PRODUCT(id),
  CONSTRAINT fk_cart_id FOREIGN KEY(cart_id) REFERENCES CART(id)
);

CREATE TABLE ORDERS
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  created TIMESTAMP DEFAULT NOW(),
  delivery TIMESTAMP NOT NULL,
  customer_id BIGINT(20) NOT NULL,
#   address_id BIGINT(20) NOT NULL,
  CONSTRAINT fk2_customer_id FOREIGN KEY(customer_id) REFERENCES CUSTOMER(id),
#   CONSTRAINT fk2_address_id FOREIGN KEY(address_id) REFERENCES ADDRESS(id)
  country VARCHAR(50),
  region VARCHAR(50),
  city VARCHAR(50),
  street VARCHAR(50),
  house VARCHAR(50),
  apartment INTEGER
);

CREATE TABLE ORDERS_ENTRY
(
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(100),
  amount INTEGER NOT NULL,
  price DOUBLE UNSIGNED,
  order_id BIGINT(20) NOT NULL,
  CONSTRAINT fk_order_id FOREIGN KEY(order_id) REFERENCES ORDERS(id)
);