# ALTER TABLE ORDERS_ENTRY DROP FOREIGN KEY fk_order_id;
# ALTER TABLE ORDERS DROP FOREIGN KEY fk2_customer_id;
# ALTER TABLE CART_ENTRY DROP FOREIGN KEY fk_cart_id;
# ALTER TABLE CART_ENTRY DROP FOREIGN KEY fk2_product_id;
# ALTER TABLE CART DROP FOREIGN KEY fk1_customer_id;
# ALTER TABLE PRODUCT DROP FOREIGN KEY fk_category_id;

DROP TABLE ORDERS_ENTRY;
DROP TABLE ORDERS;
DROP TABLE CART_ENTRY;
DROP TABLE CART;
DROP TABLE CUSTOMER;
# DROP TABLE ADDRESS;
# DROP TABLE STOCK;
# DROP TABLE BOOK;
# DROP TABLE MAGAZINE;
# DROP TABLE PICTURE;
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;